<a href="https://colab.research.google.com/github/Aswinpv787/prediction-of-graduate-admissions-from-an-indian-prospective/blob/main/Graduate_admission_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing necessary libraries**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/Internship/Admission_Predict.csv')

In [ ]:
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
395         396        324          110                  3  3.5   3.5  9.04   
396         397        325          107                  3  3.0   3.5  9.11   
397         398        330          116                  4  5.0   4.5  9.45   
398         399        312          103                  3  3.5   4.0  8.78   
399         400        333          117                  4  5.0   4.0  9.66   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
395         1              0.82  
396         1              0.84  
397         1              0.91  
398         0              0.67  
399         1              0.95  

[400 rows x 9 columns]

**missing values**

In [ ]:
df.isna().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Serial No.         400 non-null    int64  
 1   GRE Score          400 non-null    int64  
 2   TOEFL Score        400 non-null    int64  
 3   University Rating  400 non-null    int64  
 4   SOP                400 non-null    float64
 5   LOR                400 non-null    float64
 6   CGPA               400 non-null    float64
 7   Research           400 non-null    int64  
 8   Chance of Admit    400 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 28.2 KB


In [ ]:
df.describe()

Serial No.   GRE Score  TOEFL Score  University Rating         SOP  \
count  400.000000  400.000000   400.000000         400.000000  400.000000   
mean   200.500000  316.807500   107.410000           3.087500    3.400000   
std    115.614301   11.473646     6.069514           1.143728    1.006869   
min      1.000000  290.000000    92.000000           1.000000    1.000000   
25%    100.750000  308.000000   103.000000           2.000000    2.500000   
50%    200.500000  317.000000   107.000000           3.000000    3.500000   
75%    300.250000  325.000000   112.000000           4.000000    4.000000   
max    400.000000  340.000000   120.000000           5.000000    5.000000   

             LOR         CGPA    Research  Chance of Admit   
count  400.000000  400.000000  400.000000        400.000000  
mean     3.452500    8.598925    0.547500          0.724350  
std      0.898478    0.596317    0.498362          0.142609  
min      1.000000    6.800000    0.000000          0.340000  
25%      3.000000    8.170000    0.000000          0.640000  
50%      3.500000    8.610000    1.000000          0.730000  
75%      4.000000    9.062500    1.000000          0.830000  
max      5.000000    9.920000    1.000000          0.970000

In [ ]:
df.drop(['Serial No.'],axis=1,inplace=True)

In [ ]:
# Preprocessing the data
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [ ]:
x

array([[337.  , 118.  ,   4.  , ...,   4.5 ,   9.65,   1.  ],
       [324.  , 107.  ,   4.  , ...,   4.5 ,   8.87,   1.  ],
       [316.  , 104.  ,   3.  , ...,   3.5 ,   8.  ,   1.  ],
       ...,
       [330.  , 116.  ,   4.  , ...,   4.5 ,   9.45,   1.  ],
       [312.  , 103.  ,   3.  , ...,   4.  ,   8.78,   0.  ],
       [333.  , 117.  ,   4.  , ...,   4.  ,   9.66,   1.  ]])

In [ ]:
y

array([0.92, 0.76, 0.72, 0.8 , 0.65, 0.9 , 0.75, 0.68, 0.5 , 0.45, 0.52,
       0.84, 0.78, 0.62, 0.61, 0.54, 0.66, 0.65, 0.63, 0.62, 0.64, 0.7 ,
       0.94, 0.95, 0.97, 0.94, 0.76, 0.44, 0.46, 0.54, 0.65, 0.74, 0.91,
       0.9 , 0.94, 0.88, 0.64, 0.58, 0.52, 0.48, 0.46, 0.49, 0.53, 0.87,
       0.91, 0.88, 0.86, 0.89, 0.82, 0.78, 0.76, 0.56, 0.78, 0.72, 0.7 ,
       0.64, 0.64, 0.46, 0.36, 0.42, 0.48, 0.47, 0.54, 0.56, 0.52, 0.55,
       0.61, 0.57, 0.68, 0.78, 0.94, 0.96, 0.93, 0.84, 0.74, 0.72, 0.74,
       0.64, 0.44, 0.46, 0.5 , 0.96, 0.92, 0.92, 0.94, 0.76, 0.72, 0.66,
       0.64, 0.74, 0.64, 0.38, 0.34, 0.44, 0.36, 0.42, 0.48, 0.86, 0.9 ,
       0.79, 0.71, 0.64, 0.62, 0.57, 0.74, 0.69, 0.87, 0.91, 0.93, 0.68,
       0.61, 0.69, 0.62, 0.72, 0.59, 0.66, 0.56, 0.45, 0.47, 0.71, 0.94,
       0.94, 0.57, 0.61, 0.57, 0.64, 0.85, 0.78, 0.84, 0.92, 0.96, 0.77,
       0.71, 0.79, 0.89, 0.82, 0.76, 0.71, 0.8 , 0.78, 0.84, 0.9 , 0.92,
       0.97, 0.8 , 0.81, 0.75, 0.83, 0.96, 0.79, 0.

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

In [ ]:
x_train

array([[309.  , 104.  ,   2.  , ...,   2.5 ,   8.26,   0.  ],
       [304.  , 103.  ,   5.  , ...,   4.  ,   8.64,   0.  ],
       [319.  , 106.  ,   3.  , ...,   3.  ,   8.  ,   1.  ],
       ...,
       [306.  , 105.  ,   2.  , ...,   3.  ,   8.22,   1.  ],
       [302.  ,  99.  ,   1.  , ...,   2.  ,   7.25,   0.  ],
       [314.  , 106.  ,   2.  , ...,   3.5 ,   8.25,   0.  ]])

In [ ]:
x_test

array([[301.  , 104.  ,   3.  ,   3.5 ,   4.  ,   8.12,   1.  ],
       [311.  , 102.  ,   3.  ,   4.5 ,   4.  ,   8.64,   1.  ],
       [340.  , 114.  ,   5.  ,   4.  ,   4.  ,   9.6 ,   1.  ],
       [325.  , 108.  ,   4.  ,   4.5 ,   4.  ,   9.06,   1.  ],
       [301.  ,  97.  ,   2.  ,   3.  ,   3.  ,   7.88,   1.  ],
       [340.  , 115.  ,   5.  ,   4.5 ,   4.5 ,   9.45,   1.  ],
       [297.  ,  96.  ,   2.  ,   2.5 ,   1.5 ,   7.89,   0.  ],
       [303.  ,  99.  ,   3.  ,   2.  ,   2.5 ,   7.66,   0.  ],
       [312.  , 105.  ,   2.  ,   2.  ,   2.5 ,   8.45,   0.  ],
       [323.  , 113.  ,   3.  ,   4.  ,   3.  ,   9.32,   1.  ],
       [323.  , 108.  ,   3.  ,   3.5 ,   3.  ,   8.6 ,   0.  ],
       [334.  , 116.  ,   4.  ,   4.  ,   3.5 ,   9.54,   1.  ],
       [316.  , 102.  ,   3.  ,   2.  ,   3.  ,   7.4 ,   0.  ],
       [321.  , 111.  ,   5.  ,   5.  ,   5.  ,   9.45,   1.  ],
       [309.  , 105.  ,   5.  ,   3.5 ,   3.5 ,   8.56,   0.  ],
       [313.  , 107.  ,  

In [ ]:
y_train

array([0.65, 0.68, 0.65, 0.42, 0.97, 0.85, 0.73, 0.75, 0.64, 0.81, 0.84,
       0.81, 0.77, 0.82, 0.71, 0.77, 0.82, 0.71, 0.84, 0.8 , 0.64, 0.78,
       0.56, 0.77, 0.73, 0.94, 0.42, 0.69, 0.78, 0.69, 0.75, 0.71, 0.78,
       0.93, 0.52, 0.86, 0.57, 0.96, 0.54, 0.67, 0.38, 0.64, 0.92, 0.64,
       0.63, 0.74, 0.47, 0.68, 0.83, 0.71, 0.34, 0.78, 0.61, 0.48, 0.97,
       0.63, 0.86, 0.7 , 0.68, 0.95, 0.58, 0.8 , 0.57, 0.68, 0.57, 0.7 ,
       0.67, 0.74, 0.58, 0.78, 0.64, 0.75, 0.89, 0.72, 0.72, 0.75, 0.94,
       0.59, 0.73, 0.65, 0.75, 0.97, 0.8 , 0.82, 0.81, 0.92, 0.52, 0.84,
       0.81, 0.89, 0.76, 0.62, 0.73, 0.69, 0.71, 0.45, 0.51, 0.7 , 0.96,
       0.89, 0.91, 0.81, 0.93, 0.76, 0.8 , 0.72, 0.73, 0.84, 0.72, 0.69,
       0.66, 0.91, 0.86, 0.76, 0.94, 0.68, 0.67, 0.85, 0.56, 0.74, 0.71,
       0.78, 0.74, 0.72, 0.54, 0.92, 0.76, 0.91, 0.77, 0.76, 0.79, 0.63,
       0.72, 0.58, 0.91, 0.57, 0.55, 0.76, 0.7 , 0.84, 0.52, 0.78, 0.88,
       0.46, 0.68, 0.92, 0.79, 0.49, 0.75, 0.42, 0.

In [ ]:
y_test

array([0.68, 0.68, 0.9 , 0.79, 0.44, 0.94, 0.43, 0.36, 0.72, 0.85, 0.45,
       0.93, 0.64, 0.93, 0.71, 0.53, 0.66, 0.34, 0.74, 0.96, 0.64, 0.54,
       0.71, 0.54, 0.92, 0.84, 0.59, 0.61, 0.7 , 0.74, 0.82, 0.94, 0.71,
       0.46, 0.69, 0.56, 0.72, 0.58, 0.61, 0.9 , 0.73, 0.64, 0.74, 0.94,
       0.92, 0.82, 0.96, 0.71, 0.94, 0.89, 0.86, 0.73, 0.81, 0.94, 0.39,
       0.48, 0.71, 0.86, 0.65, 0.86, 0.57, 0.61, 0.79, 0.44, 0.64, 0.74,
       0.64, 0.83, 0.89, 0.84, 0.75, 0.84, 0.9 , 0.88, 0.49, 0.72, 0.64,
       0.67, 0.9 , 0.79, 0.8 , 0.63, 0.97, 0.74, 0.58, 0.56, 0.8 , 0.66,
       0.93, 0.64, 0.64, 0.83, 0.47, 0.76, 0.71, 0.66, 0.79, 0.78, 0.59,
       0.72, 0.71, 0.61, 0.66, 0.61, 0.79, 0.68, 0.62, 0.71, 0.73, 0.62,
       0.77, 0.53, 0.56, 0.46, 0.86, 0.48, 0.46, 0.93, 0.74, 0.8 ])

In [ ]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
scalar.fit(x_train)
x_train=scalar.fit_transform(x_train)
x_test=scalar.fit_transform(x_test)
x_test

array([[-1.28059695, -0.47153952, -0.02963044,  0.12137714,  0.64105642,
        -0.7810706 ,  0.96720415],
       [-0.42448757, -0.79673919, -0.02963044,  1.16175267,  0.64105642,
         0.08462754,  0.96720415],
       [ 2.05822963,  1.15445883,  1.74819611,  0.64156491,  0.64105642,
         1.6828395 ,  0.96720415],
       [ 0.77406556,  0.17885982,  0.85928283,  1.16175267,  0.64105642,
         0.78384527,  0.96720415],
       [-1.28059695, -1.60973836, -0.91854372, -0.39881062, -0.53339809,
        -1.18062359,  0.96720415],
       [ 2.05822963,  1.31705866,  1.74819611,  1.16175267,  1.22828367,
         1.43311888,  0.96720415],
       [-1.6230407 , -1.7723382 , -0.91854372, -0.91899838, -2.29507984,
        -1.16397555, -1.03390789],
       [-1.10937507, -1.28453869, -0.02963044, -1.43918615, -1.12062534,
        -1.54688049, -1.03390789],
       [-0.33887663, -0.30893969, -0.91854372, -1.43918615, -1.12062534,
        -0.23168524, -1.03390789],
       [ 0.60284369,  0.9918

In [ ]:
from sklearn.tree import DecisionTreeRegressor
model=DecisionTreeRegressor()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
y_pred

array([0.59, 0.85, 0.93, 0.89, 0.48, 0.91, 0.68, 0.48, 0.81, 0.93, 0.52,
       0.95, 0.49, 0.91, 0.76, 0.65, 0.67, 0.47, 0.66, 0.97, 0.67, 0.7 ,
       0.68, 0.56, 0.95, 0.84, 0.75, 0.67, 0.79, 0.84, 0.79, 0.94, 0.73,
       0.52, 0.72, 0.71, 0.57, 0.73, 0.73, 0.92, 0.84, 0.7 , 0.8 , 0.94,
       0.88, 0.8 , 0.97, 0.62, 0.94, 0.9 , 0.92, 0.71, 0.74, 0.95, 0.49,
       0.62, 0.62, 0.8 , 0.65, 0.88, 0.7 , 0.42, 0.77, 0.47, 0.59, 0.52,
       0.65, 0.78, 0.88, 0.78, 0.73, 0.81, 0.93, 0.9 , 0.54, 0.77, 0.72,
       0.68, 0.86, 0.78, 0.78, 0.75, 0.97, 0.73, 0.49, 0.72, 0.8 , 0.79,
       0.94, 0.66, 0.65, 0.84, 0.57, 0.77, 0.63, 0.64, 0.71, 0.76, 0.56,
       0.81, 0.63, 0.7 , 0.71, 0.78, 0.77, 0.66, 0.7 , 0.62, 0.74, 0.65,
       0.68, 0.73, 0.42, 0.48, 0.86, 0.65, 0.46, 0.92, 0.79, 0.78])

In [ ]:
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error
mse=mean_squared_error(y_test,y_pred)
rmse = mean_squared_error(y_test, y_pred, squared=False)
r2=r2_score(y_test,y_pred)
mae = mean_absolute_error(y_test, y_pred)

In [ ]:
print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)
print("R2 Score:", r2)
print('mean_absolute_error:',mae)

Mean Squared Error: 0.007026666666666666
Root Mean Squared Error: 0.08382521498133283
R2 Score: 0.6913149378383259
mean_absolute_error: 0.0625
